forminput props overhaul, central colours
Doubrixel/digitalisierung-at-school pull request #10
Opened 2021-09-09 19:33 UTC by Jojo2412

including onClick function, diverse label width, text, name

2021-09-13 18:14 UTC, Jojo2412 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Formular für die 5. Prüfungskomponente (1. Schritt)](https://trello.com/c/GaY0sMTZ/19-formular-f%C3%BCr-die-5-pr%C3%BCfungskomponente-1-schritt)

2021-09-16 06:34 UTC, Blackie11elf requested changes

2021-09-16 06:34 UTC, Blackie11elf commented on frontend/src/components/FormInput/forminputElementRadioButton.tsx
> +function RadioButtonFormInputFifthExamComponent(
Die Komponente am Besten so nennen wie die Datei

2021-09-16 11:23 UTC, Ructabo commented
For some reason, the first button gets clicked when another button outside of the small radio button gets clicked.

2021-09-16 11:59 UTC, merged