Wahlpflicht entry page
Doubrixel/digitalisierung-at-school pull request #19
Opened 2021-09-16 12:01 UTC by Ructabo

2021-09-16 12:02 UTC, Ructabo commented
![](https://github.trello.services/images/mini-trello-icon.png) [Wahlfplicht](https://trello.com/c/PtedJzn2/16-wahlfplicht)

2021-09-17 09:38 UTC, Blackie11elf requested changes
Bei Fragen gerne direkt zu mir kommen :D

2021-09-17 09:38 UTC, Blackie11elf commented on frontend/src/components/FormInput/ForminputElementRadioButton.tsx
> +      {/* eslint-disable-next-line jsx-a11y/label-has-associated-control */}
Kommentar, warum eslint disabled wurde fehlt

2021-09-17 09:38 UTC, Blackie11elf commented on frontend/src/components/FormInput/ForminputElementSubmitButton.tsx
> +function ForminputElementSubmitButton({ onClickMethod }: { onClickMethod:()=>void }) {
Nur ne Frage: ist das { onClickMethod:()=>void } der DefaultValue, wenn onClickMethod nicht übergeben wurde? Aber die prop is ja required? Oder was macht das?

2021-09-17 09:38 UTC, Blackie11elf commented on frontend/src/components/FormInput/ForminputElementText.tsx
> +      {/* eslint-disable-next-line jsx-a11y/label-has-associated-control */}
Kommentar, warum eslint disabled wurde fehlt

2021-09-17 09:38 UTC, Blackie11elf commented on frontend/src/pages/WahlpflichtEntryPage.tsx
> +          <h3>1. Wahlpflichtfach</h3>
Auch wenn wir erst noch das Design implementieren, kann man schonmal sowas bauen wie:
man bekommt ein Array an Wahlpflichtfächern, das mappt man dann zu den Komponenten.

arrayOfWahlpflichtFaecher.map(fach => {return(
<ForminputRadioButton labelText={fach} ...andere props... />
)})

Wenn du dazu Fragen hast, komm einfach zu mir. Können wir auch gerne zusammen machen.

2021-09-17 09:38 UTC, Blackie11elf commented on frontend/src/pages/WahlpflichtEntryPage.css
> +    #Wahlpflichtfach1{
da Wahlfplichtfach1 mehrmals auftaucht lieber mit Klassen statt ids arbeiten.

2021-09-17 09:38 UTC, Blackie11elf commented on frontend/src/pages/WahlpflichtEntryPage.tsx
> +          <ForminputElementRadioButton labelText="Deutsch" name="Wahlpflichtfach1" maxLabelWidth={maxLabelWidth} minLabelWidth={minLabelWidth} />
Was genau macht das name="Wahlpflichtfach1" ? da bin ich mir echt grad nicht sicher. Wenn es für die css-Styles ist, dass nutze da lieber className="Wahlpflichtfach1" und nutze css-Klassen im css file

2021-09-17 09:38 UTC, Blackie11elf commented on frontend/src/pages/WahlpflichtEntryPage.tsx
> +const maxLabelWidth = '300px';
maxwidth kann ruhig größer. Man hat den Platz ja auf dem Bildschirm. Du hast es wahrscheinlich jetzt so eingestellt, dass die maxWidth grad groß genug ist, wenn der Bildschirm bei 550px ist und dann kommen die wahlpflichtfächer untereinander sodass nix überlappt. Das resultiert aber daraus, dass du bei größeren Fenstern viel weißen platz hast.

Für das Problem hat css eine Einheit: "1vw" (view width") Ist so ähnlich wie %, nur bezieht sich % auf das parentElement. vw auf den viewport, also wie groß dein Fenster ist. 1vw ist 1% der fensterbreite.

https://www.mediaevent.de/schriftgroessen-immer-ein-griff-ins-wespennest/ Da gibts noch mehr infos drüber wenn du willst.

Probier das mal mit vw oder % umzusetzen.
(ProTip: Gibts auch für height. die einheit heißt dann "vh" (view height)

2021-09-29 07:47 UTC, Blackie11elf requested changes

2021-09-29 07:47 UTC, Blackie11elf commented on frontend/src/pages/WahlpflichtEntryPage.css
> +    width: 90vw;
mach die width von dem paper mal raus. ich hab im root div ein padding eingebaut, sodass keine child komponenten an den rand stoßen. das mit der width hier wäre doppelt gemoppelt.

Konntest du halt nicht wissen :/

2021-09-29 07:47 UTC, Blackie11elf commented on frontend/src/pages/WahlpflichtEntryPage.css
> +#pageRoot {
die ganzen pageroot eigenschaften kommen von App.js. musst du hier nix einbauen. Sobald alles aufm master zusammen gemerged ist, wird das ordentlich aussehen

2021-09-29 09:23 UTC, merged