AGBuchung
Doubrixel/digitalisierung-at-school pull request #24
Opened 2021-09-21 08:14 UTC by Wilhelm-kaden

Es ist ein grobes Konzept für die einzelnen AG-Seiten.

2021-09-21 18:01 UTC, Jan1208 commented
![](https://github.trello.services/images/mini-trello-icon.png) [einzelne AG](https://trello.com/c/iUxUTjn1/18-einzelne-ag)

2021-09-21 18:09 UTC, Jan1208 requested changes
An der Trello Karte ist auch noch ein Fehler bei kleineren Bildschirmen

2021-09-21 18:09 UTC, Jan1208 commented on frontend/src/pages/AGEntryPage.tsx
>  function AGEntryPage() {
diese Komponente ist eigentlich die Komponente wo alle AG's die für einen Schüler verfügbar sind angezeigt werden, also dass was Max gerade macht.

Du kannst deins ja in eine extra Komponente packen, sowas wie "DetailAGInfoPage". Im Rounting in der App.tsx muss für diese dann eine extra Seite angelegt werden

2021-09-21 18:09 UTC, Jan1208 commented on frontend/src/pages/AGEntryPage.tsx
> +      <input
das sollte hier kein Textfeld, sondern ein Button sein --> dafür den Button aus material ui wählen

2021-09-21 18:09 UTC, Jan1208 commented on frontend/src/pages/AGEntryPage.tsx
> +      <input
das sollte auch kein input-Feld sein, sondern einfach ein normaler Text. Der Nutzer soll hier ja nichts verändern

2021-09-21 18:09 UTC, Jan1208 commented on frontend/src/pages/AGEntryPage.tsx
> +        type="submit"
Bitte den Button von material ui nehmen

2021-09-27 08:25 UTC, Wilhelm-kaden commented
![](https://github.trello.services/images/mini-trello-icon.png) [einzelne AG](https://trello.com/c/iUxUTjn1/18-einzelne-ag)

2021-09-27 09:35 UTC, Jan1208 reviewed
Bitte nochmal anschauen, haben wir ja gerade besprochen.
Gibt noch paar Kleinigkeiten bei der responsivität und dass die Anzeige der Verfügbarkeit ein Button ist.

2021-09-27 15:50 UTC, closed without merging