CSS-Anpassungen, für größere Bildschirme
Doubrixel/digitalisierung-at-school pull request #27
Opened 2021-09-21 17:32 UTC by Jan1208

- statt px -> vw verwendet
- Text des Login-Button größer gemacht

2021-09-21 17:33 UTC, Jan1208 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Toolbar 4k](https://trello.com/c/DNMzMTOI/31-toolbar-4k)

2021-09-27 09:53 UTC, Blackie11elf requested changes

2021-09-27 09:53 UTC, Blackie11elf commented on frontend/src/components/Toolbar/LoginLogoutButton/LoginLogoutButton.css
> +  width: 175px;
statt den login container mit width und padding an die richtige stelle zu schubsen kann man auch den link container zu einer flexbox machen und dann justify-content: space-between oder space-around oder space-evenly.
Dann muss man auch für die navlinks keine extra margin jedes mal

2021-09-27 09:53 UTC, Blackie11elf commented on frontend/src/components/Toolbar/Toolbar.css
> +  padding: 1em;
em und rem sind ja eigentlich einheiten für font sizing. nutz da mal lieber vw

2021-09-27 10:21 UTC, merged