Start_Komponente_Angepasst
Doubrixel/digitalisierung-at-school pull request #29
Opened 2021-09-24 14:49 UTC by derSchumann

Die Auswahlkomponente vom Startbildschirm wurde nun so angepasst, das es auch auf einem 4K Bildschirm passt.

2021-09-24 14:50 UTC, derSchumann commented
![](https://github.trello.services/images/mini-trello-icon.png) [Toolbar 4K](https://trello.com/c/AFiJ5N9U/33-toolbar-4k)

2021-09-27 07:45 UTC, Blackie11elf requested changes

2021-09-27 07:45 UTC, Blackie11elf commented on frontend/src/components/ModulSelectionComponent/SelectionComponent.css
>  .SelcetionButton {
Typo

2021-09-27 07:45 UTC, Blackie11elf commented on frontend/src/components/ModulSelectionComponent/SelectionComponent.css
> +  .SelcetionButton {
Gleicher Typo. Den wirds wohl überall bei dem Button geben

2021-09-27 07:47 UTC, Blackie11elf commented
![grafik](https://user-images.githubusercontent.com/70255426/134865838-125b583a-2cc8-4e6b-8b48-b8658805bc9d.png)
Da wird der text manchmal von dem button überdeckt, dadurch dass die margin vh ist. Die margin gilt allerdings nicht zum button, da position: absolute den button aus dem flow rauslöst und dadurch dinge überdecken kann. siehe auch: https://developer.mozilla.org/de/docs/Web/CSS/position

Lösungsvorschlag: margin vergrößern oder mit einer fixen einheit (px) machen

2021-09-28 08:47 UTC, merged