Admin einzelner Schüler
Doubrixel/digitalisierung-at-school pull request #72
Opened 2021-11-26 14:21 UTC by Wilhelm-kaden

2021-11-26 14:23 UTC, Wilhelm-kaden commented
![](https://github.trello.services/images/mini-trello-icon.png) [Einzelne Ansicht für Schule (Facharbeit)](https://trello.com/c/Kjmx02R3/72-einzelne-ansicht-f%C3%BCr-schule-facharbeit)

2021-11-28 12:55 UTC, Blackie11elf requested changes

2021-11-28 12:55 UTC, Blackie11elf commented on frontend/src/pages/admin/AdminEinzelnerSchueler/AdminFacharbeitApplicationForm.tsx
> +      body: requestBody,
der requestBody muss als JSON vorliegen, daher macht in der Zeile: body: JSON.stringify(requestBody),

2021-11-28 12:55 UTC, Blackie11elf commented on frontend/src/pages/admin/AdminEinzelnerSchueler/AdminFacharbeitApplicationForm.tsx
> +          <FormControl style={{ width: '100%', marginTop: '32px' }} variant="outlined">
Fach sind jetzt Freitextfelder, keine Dropdowns mehr

2021-11-28 12:55 UTC, Blackie11elf commented on frontend/src/pages/admin/AdminEinzelnerSchueler/AdminFacharbeitApplicationForm.tsx
> +          <FormControl style={{ width: '100%', marginTop: '3vh' }} variant="outlined">
Lehrkräfte werden auch als Freiotextfeld eingetragen

2021-11-28 12:55 UTC, Blackie11elf commented on frontend/src/pages/admin/AdminEinzelnerSchueler/AdminFacharbeitApplicationForm.tsx
> +          <FormControl style={{ width: '100%', marginTop: '3vh' }} variant="outlined">
gleiches hier, Freitextfeld statt Dropdown

2021-11-28 12:55 UTC, Blackie11elf commented on frontend/src/pages/admin/AdminEinzelnerSchueler/AdminFacharbeitEntryPage.tsx
> +  const [role] = useState('student');
bei einer Reacthook brauchst du immer ein Variable und ein setter, das sieht dann so aus: 
const [role, setRole] = useState('student');

der defaultvalue, also jetzt wo dort 'student' drinsteht sollte leer sein (bzw. leerer string), und über eine useEffect Hook initial gesetzt werden. Die useEffect Hook wird grundsätzlich einmal ausgeführt wenn die Funktionale Komponente geladen wird und kann dann sie noch abhängig von verschiedenen werten, die im dependency array stehen, ausgeführt werden. Der Syntax sieht so aus:

  useEffect(() => {
// hier code der ausgeführt werden soll
  }, [ dependency array]);

in der useEffect kannst du dann die role aus dem redux state lesen und mit "setRole(*roleAusReduxState*); setzen

2021-11-28 12:55 UTC, Blackie11elf commented on frontend/src/pages/admin/AdminEinzelnerSchueler/AdminFacharbeitStudentListPage.tsx
> +      <TableListComponent columnHeaders={['Schüler:in', 'Thema', '1. Lehrkraft', '2. Lehrkraft']} tableStyleObject={{ width: '95vw' }} />
Hattest du hier nicht diese fancy table von materialUI die wir nutzen wollten? oder ist das hier noch ein alter stand?

2021-12-01 15:49 UTC, Blackie11elf requested changes

2021-12-01 15:49 UTC, Blackie11elf commented on frontend/src/pages/student/Facharbeit/FacharbeitApplicationForm.tsx
> +    const requestBody = JSON.stringify({
{String topic, String subject, String choosenTeacher, String subjectTeacher}
Das sind die parameternamen die laut schnittstellendoku im backend erwartet werden. die namen musst du in deinem requestBody auch verwenden, sonst weiß das backend ja nicht welcher parameter welcher ist. die reinfolge spielt keine rolle, nur die Namen

2021-12-01 15:49 UTC, Blackie11elf commented on frontend/src/pages/student/Facharbeit/FacharbeitApplicationForm.tsx
> +          }
Nur so als Anmerkung, musst du nicht umsetzen:
Aber du hättest auch einen Button nehmen können und die beschriftung und on ClickMethode mit ternären ausdrücken abhängig vom formStatus machen können:
{formStatus === 3 ? 'FAcharbeit ändern' : 'Facharbeit einreichen'} und analog in der onClick mit der handlerFunction

2021-12-03 14:47 UTC, Blackie11elf requested changes

2021-12-03 14:47 UTC, Blackie11elf commented on frontend/src/pages/student/Facharbeit/FacharbeitApplicationForm.tsx
> +    const requestBody = JSON.stringify({
wenn du ein JS object übergibst, dann ist die notation so: {key: value}

was du jetzt gemacht hast ist die values umbenennen.

kleines Bsp: du hast dein requestBody so definiert: 
requestbody = {topic: topicArea}
wenn du jetzt den wert von topicArea auf 'asdf' setzt, dann sieht dein objekt so aus:
{topicArea: 'asdf'}

aber wenn du dein requestBody so definierst: requestBody = {topic: blablablubb} und du den wert blablablubb auf 'asdf' setzt, dann sieht dein resultierendes objekt genauso aus wie im ersten Bsp. da der name des values ja ersetzt wird.

Heißt zusammengefasst: das objekt {topic: topicArea} und das objekt {topic: blablablubb} sehen genau gleich aus, wenn topicArea und blablablubb den gleichen wert haben.

deshalb schaut wer auch immer das objekt übergeben bekommt nicht auf den namen des values, den du vergibst, sonder auf den namen des key.

zusammengefasst: wenn das backend einen parameter "subject" erwartet, dann musst du den key auch "subject" nennen und nicht den value, da der value ja zum schluss durch einen wert ersetzt wird

2021-12-06 06:30 UTC, Blackie11elf requested changes

2021-12-06 06:30 UTC, Blackie11elf commented on frontend/src/pages/student/Facharbeit/FacharbeitApplicationForm.tsx
> +      studentId: 0,
parameter wird nicht benötigt

2021-12-06 06:30 UTC, Blackie11elf commented on frontend/src/pages/student/Facharbeit/FacharbeitApplicationForm.tsx
>        studentId: 0,
parameter wird nicht benötigt

2021-12-06 07:03 UTC, merged